---
abstract: 'non-blocking wrapper around WWW::XKCD::AsText'
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-WWW-XKCD-AsText
provides:
  POE::Component::WWW::XKCD::AsText:
    file: lib/POE/Component/WWW/XKCD/AsText.pm
    version: 0.002
requires:
  Carp: 1.04
  POE: 0.9999
  POE::Filter::Line: 1.2222
  POE::Filter::Reference: 1.222
  POE::Wheel::Run: 1.2222
  WWW::XKCD::AsText: 0.001
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.002
